# Generated by Django 4.1 on 2023-09-02 14:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('prev_date', models.DateTimeField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('visited', models.FloatField(default=1)),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='General', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('msg', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=100, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('GSTIN', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('account', models.TextField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('whatsapp', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('Grocery', 'Grocery'), ('Supermarket', 'Supermarket'), ('Vegetables', 'Vegetables'), ('Hotel', 'Hotel')], default='Grocery', max_length=100)),
                ('type', models.CharField(choices=[('Retail', 'Retail'), ('Wholesale', 'Wholesale'), ('Hotel', 'Hotel'), ('Distribution', 'Distribution')], default='Retail', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('balance', models.FloatField(default=0)),
                ('route', models.CharField(default='General', max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='shope_profile.jpg', upload_to='')),
                ('party_type', models.CharField(choices=[('seller', 'seller'), ('buyer', 'buyer'), ('both', 'both')], default='seller', max_length=15)),
                ('party_group', models.CharField(default='fasal', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=5, null=True, unique=True)),
                ('last_id', models.IntegerField(default=0)),
                ('used', models.CharField(choices=[('order', 'order'), ('sale', 'sale'), ('return', 'return'), ('payment', 'payment')], max_length=100)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100, unique=True)),
                ('size', models.CharField(max_length=100)),
                ('r_price', models.FloatField()),
                ('w_price', models.FloatField()),
                ('h_price', models.FloatField()),
                ('d_price', models.FloatField()),
                ('HSN', models.FloatField(default=0)),
                ('mrp', models.FloatField()),
                ('barcode', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField(default=0)),
                ('iid', models.CharField(max_length=100, unique=True)),
                ('party_type', models.CharField(default='Retail', max_length=100)),
                ('date', models.DateTimeField(null=True)),
                ('t_type', models.CharField(choices=[('order', 'order'), ('sale', 'sale'), ('return', 'return'), ('payment', 'payment')], max_length=100)),
                ('total', models.FloatField(default=0)),
                ('t_total', models.FloatField(default=0, max_length=25)),
                ('q_total', models.FloatField(default=0, max_length=25)),
                ('fq_total', models.FloatField(default=0, max_length=25)),
                ('received', models.FloatField(default=0, max_length=25)),
                ('p_type', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Gpay', 'Gpay')], default='Cash', max_length=10)),
                ('balance', models.FloatField(max_length=25, null=True)),
                ('report', models.TextField(blank=True, max_length=500, null=True)),
                ('ir_date', models.DateTimeField(blank=True, null=True)),
                ('ir_iid', models.CharField(blank=True, max_length=50, null=True)),
                ('id_prefix', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sale_order.prefix')),
                ('party_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sale_order.party')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_order', models.BooleanField(default=True)),
                ('home_daybook', models.BooleanField(default=True)),
                ('home_sale', models.BooleanField(default=True)),
                ('home_credit', models.BooleanField(default=False)),
                ('home_expense', models.BooleanField(default=True)),
                ('inv_view_tax', models.BooleanField(default=True)),
                ('inv_view_round', models.BooleanField(default=True)),
                ('inv_pdf_tax', models.BooleanField(default=True)),
                ('inv_pdf_round', models.BooleanField(default=True)),
                ('inv_pdf_balance', models.BooleanField(default=False)),
                ('inv_pdf_column', models.IntegerField(default=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('t_price', models.FloatField(null=True)),
                ('gst', models.FloatField(null=True)),
                ('qty', models.FloatField(null=True)),
                ('fqty', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('t_amount', models.FloatField(default=0)),
                ('iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale_order.sale')),
                ('p_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale_order.products')),
                ('party_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale_order.party')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('report', models.CharField(max_length=100)),
                ('category', models.CharField(default='report', max_length=100)),
                ('disc', models.TextField(blank=True, max_length=500, null=True)),
                ('party_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale_order.party')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(default='Staff', max_length=200)),
                ('balance', models.FloatField(default=0)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('salary', models.CharField(blank=True, max_length=50)),
                ('phone_2', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('gpay', models.CharField(blank=True, max_length=50, null=True)),
                ('account', models.CharField(blank=True, max_length=100)),
                ('ifsc', models.CharField(blank=True, max_length=50)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='Information', max_length=200)),
                ('process', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 9, 2, 20, 4, 43, 877017))),
                ('expense', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('disc', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 9, 2, 20, 4, 43, 877353))),
                ('p_type', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
