# Generated by Django 4.1 on 2023-09-02 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 20, 11, 0, 686868)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 20, 11, 0, 686526)),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='iid',
            field=models.CharField(max_length=100),
        ),
    ]
